# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/akonovalov/Documents/bigolchungus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/akonovalov/Documents/bigolchungus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/akonovalov/Documents/bigolchungus/CMakeFiles /Users/akonovalov/Documents/bigolchungus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/akonovalov/Documents/bigolchungus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bigolchungus

# Build rule for target.
bigolchungus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bigolchungus
.PHONY : bigolchungus

# fast build rule for target.
bigolchungus/fast:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/build
.PHONY : bigolchungus/fast

blake2s_ref.o: blake2s_ref.c.o

.PHONY : blake2s_ref.o

# target to build an object file
blake2s_ref.c.o:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/blake2s_ref.c.o
.PHONY : blake2s_ref.c.o

blake2s_ref.i: blake2s_ref.c.i

.PHONY : blake2s_ref.i

# target to preprocess a source file
blake2s_ref.c.i:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/blake2s_ref.c.i
.PHONY : blake2s_ref.c.i

blake2s_ref.s: blake2s_ref.c.s

.PHONY : blake2s_ref.s

# target to generate assembly for a file
blake2s_ref.c.s:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/blake2s_ref.c.s
.PHONY : blake2s_ref.c.s

common.o: common.cpp.o

.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i

.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s

.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/common.cpp.s
.PHONY : common.cpp.s

opencl_backend.o: opencl_backend.cpp.o

.PHONY : opencl_backend.o

# target to build an object file
opencl_backend.cpp.o:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/opencl_backend.cpp.o
.PHONY : opencl_backend.cpp.o

opencl_backend.i: opencl_backend.cpp.i

.PHONY : opencl_backend.i

# target to preprocess a source file
opencl_backend.cpp.i:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/opencl_backend.cpp.i
.PHONY : opencl_backend.cpp.i

opencl_backend.s: opencl_backend.cpp.s

.PHONY : opencl_backend.s

# target to generate assembly for a file
opencl_backend.cpp.s:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/opencl_backend.cpp.s
.PHONY : opencl_backend.cpp.s

test_opencl.o: test_opencl.cpp.o

.PHONY : test_opencl.o

# target to build an object file
test_opencl.cpp.o:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/test_opencl.cpp.o
.PHONY : test_opencl.cpp.o

test_opencl.i: test_opencl.cpp.i

.PHONY : test_opencl.i

# target to preprocess a source file
test_opencl.cpp.i:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/test_opencl.cpp.i
.PHONY : test_opencl.cpp.i

test_opencl.s: test_opencl.cpp.s

.PHONY : test_opencl.s

# target to generate assembly for a file
test_opencl.cpp.s:
	$(MAKE) -f CMakeFiles/bigolchungus.dir/build.make CMakeFiles/bigolchungus.dir/test_opencl.cpp.s
.PHONY : test_opencl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bigolchungus"
	@echo "... blake2s_ref.o"
	@echo "... blake2s_ref.i"
	@echo "... blake2s_ref.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... opencl_backend.o"
	@echo "... opencl_backend.i"
	@echo "... opencl_backend.s"
	@echo "... test_opencl.o"
	@echo "... test_opencl.i"
	@echo "... test_opencl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

